[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jupyter-utility-widgets"
version = "0.0.1"
readme = "README.md"
dependencies = [
    "ipywidgets>=8.0.2"
]